-- MySQL Script generated by MySQL Workbench
-- Mon Jul 16 10:51:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PlannerDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PlannerDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PlannerDB` DEFAULT CHARACTER SET utf8 ;
USE `PlannerDB` ;

-- -----------------------------------------------------
-- Table `PlannerDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlannerDB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first` VARCHAR(45) NULL,
  `last` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlannerDB`.`weddings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlannerDB`.`weddings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `WedderOne` VARCHAR(45) NULL,
  `WedderTwo` VARCHAR(45) NULL,
  `WeddingDate` DATE NULL,
  `WeddingStrAdd` VARCHAR(45) NULL,
  `RSVPcount` VARCHAR(45) NULL,
  `CreatorId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_weddings_users_idx` (`CreatorId` ASC),
  CONSTRAINT `fk_weddings_users`
    FOREIGN KEY (`CreatorId`)
    REFERENCES `PlannerDB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlannerDB`.`RSVP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlannerDB`.`RSVP` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `GuestId` INT NOT NULL,
  `WeddingId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RSVP_users1_idx` (`GuestId` ASC),
  INDEX `fk_RSVP_weddings1_idx` (`WeddingId` ASC),
  CONSTRAINT `fk_RSVP_users1`
    FOREIGN KEY (`GuestId`)
    REFERENCES `PlannerDB`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RSVP_weddings1`
    FOREIGN KEY (`WeddingId`)
    REFERENCES `PlannerDB`.`weddings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
